name: Gambarra
description: Consultoria e Treinamentos

markdown: kramdown
highlighter: rouge
paginate: 15
baseurl: /
domain_name: 'http://gambarra.github.com'
google_analytics: 'UA-115519525-1'

# Details for the RSS feed generator
url: 'http://gambarra.com'

author:
    name: Thiago Gambarra
    thumb: /assets/images/profile.jpg
    bio: Desenvolvedor de Software e cozinheiro amador nas horas vagas.
    url:
        site: 'http://gambarra.com'
        facebook: 'https://www.facebook.com/thiago.daluzgambarra'
        linkedin: 'https://www.linkedin.com/in/thiago-gambarra-258b4329/'
        email: 'thiago.gambarra@gmail.com'

urls:
    about: /sobre

img_path: /assets/images/

plugins:
    - jekyll-seo-tag